# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='location_id',
            field=models.CharField(default='random id', help_text='need to use FK once location model is built', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='meta_data',
            field=models.CharField(blank=True, help_text='All other available info of this record. Served as 1. Notes. OR 2. Extra info to support backfill should new fields are needed from here.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='modify_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='guid',
            field=models.CharField(blank=True, default=uuid.uuid4, help_text='Unique, externally-friendly identifier', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_accuracy',
            field=models.CharField(help_text='confidence level of the position_[x|y|orientation] values', max_length=30),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_orientation',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="entity's facing direction, for example facing north takes value '0', facing southwest takes value '225'.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_x',
            field=models.DecimalField(decimal_places=6, help_text="horizontal axis value in current location's coordinate system", max_digits=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_y',
            field=models.DecimalField(decimal_places=6, help_text="vertical axis value in current location's coordinate system", max_digits=10),
        ),
    ]
