# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-17 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20170917_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitposition',
            name='position_x_left',
            field=models.DecimalField(decimal_places=6, default=0, help_text=' horizontal axis value for left boundary of the visible rectangle.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitposition',
            name='position_x_right',
            field=models.DecimalField(decimal_places=6, default=5, help_text=' horizontal axis value for right boundary of the visible rectangle.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitposition',
            name='position_y_lower',
            field=models.DecimalField(decimal_places=6, default=2, help_text=' vertical axis value for lower boundary of the visible rectangle.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitposition',
            name='position_y_upper',
            field=models.DecimalField(decimal_places=6, default=8, help_text=' vertical axis value for upper boundary of the visible rectangle.', max_digits=10),
            preserve_default=False,
        ),
    ]
