# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-18 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20170917_2345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPosition',
            new_name='UserPositionHistory',
        ),
    ]
