# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, default=uuid.uuid4, help_text='Unique, externally-friendly identifier', max_length=36, unique=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modify_dt', models.DateTimeField(auto_now=True, null=True)),
                ('meta_data', models.CharField(blank=True, help_text='All other available info of this record. Served as 1. Notes. OR 2. Extra info to support backfill should new fields are needed from here.', max_length=200, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('action_type', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExhibitAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, default=uuid.uuid4, help_text='Unique, externally-friendly identifier', max_length=36, unique=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('modify_dt', models.DateTimeField(auto_now=True, null=True)),
                ('meta_data', models.CharField(blank=True, help_text='All other available info of this record. Served as 1. Notes. OR 2. Extra info to support backfill should new fields are needed from here.', max_length=200, null=True)),
                ('details', models.CharField(help_text='indicate action type, # TODO: will improve this field', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
