# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-17 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModernModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, default=uuid.uuid4, help_text='Unique, externally-friendly identifier', max_length=36, unique=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('meta_data', models.CharField(blank=True, help_text='All other available info of this record. Used for backfill should new fields are introduced from here.', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exhibitaction',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exhibitaction',
            name='details',
            field=models.CharField(help_text='indicate action type, # TODO: will improve this field', max_length=200),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('modernmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='action.ModernModel')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('action_type', models.CharField(blank=True, max_length=50, unique=True)),
            ],
            bases=('action.modernmodel',),
        ),
    ]
